### ISSUE TITLE
Unable to provide full path to .xccoverage file

### ISSUE THREAD

**Issue by raven** [fastlane-community/xcov#108]
There is error output here that states that you can provide a full path to the .xccoverage file:
https://github.com/nakiostudio/xcov/blob/b4d00172e7277adae5f28f8fe36c19af33600499/lib/xcov/error_handler.rb#L12

However there is no mechanism to provide a full path to the .xccoverage file that I can see within: [manager.rb](https://github.com/nakiostudio/xcov/blob/a7dbd6a2901b8944a692c2a2ab32289135044f73/lib/xcov/manager.rb)

**Comment by eelcokoelewijn-afrogleap** [comment]
@raven Not sure if you are using Xcode 9.2 or Xcode 9.3, if you are using Xcode 9.2 with the latest version of Xcov 1.4. You can set the `legacy_support` parameter to `xccoverage` in your fastfile to parse the coverage reports generated by Xcode 9.2. No need to specify a path.

@nakiostudio Maybe you can update the README for the `legacy_support` parameter, so it explains the `legacy_support` parameter is a string value, containing either: `xccoverage` or the default value `xccovreport`.

**Comment by cisum-la** [comment]
I used below command as i am using Xcode 9.2:
xcov --legacy_support xccoverage [Path_to_coverage_file]

But getting below error:
[14:53:06]: Unable to find any .xccoverage file.
[14:53:06]: Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
[14:53:06]: Alternatively you can provide the full path to your .xccoverage file.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	13: from /usr/local/bin/xcov:23:in `<main>'
	12: from /usr/local/bin/xcov:23:in `load'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/bin/xcov:6:in `<top (required)>'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/commands_generator.rb:15:in `start'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/commands_generator.rb:46:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.92.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/commands_generator.rb:41:in `block (2 levels) in run'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/manager.rb:30:in `run'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/manager.rb:45:in `parse_xccoverage'
/usr/local/lib/ruby/gems/2.5.0/gems/xcov-1.4.0/lib/xcov/error_handler.rb:20:in `handle_error': [!] Error creating your coverage report - see the log above (RuntimeError)

**Comment by eelcokoelewijn-afrogleap** [comment]
@cisum-la I think the path is not needed. So the command is: `xcov --legacy_support xccoverage` Xcov then uses the old way of finding and collecting information from .xccoverage file.

**Comment by raven** [comment]
This was resolved by https://github.com/fastlane-community/xcov/pull/150
