### ISSUE TITLE
xcov should allow passing xcresult path

### ISSUE THREAD

**Issue by abotkin-cpi** [fastlane-community/xcov#156]
Similar to the work that was done to allow for passing the code coverage file directly #150, it would be nice if xcov would allow for passing the xcresult path directly.  In some cloud CI systems, users are given the path to the xcresult, but it is not kept within the derived data folder and is instead in some temporary directory.  If xcov could take the path to the xcresult, it could avoid having to try and do its own search for the correct xcresult to parse & allow for folks to take advantage of xcov's parsing of the Xcode 11 xcresult format.

**Comment by joshdholtz** [comment]
@abotkin-cpi You can with the `:xccov_file_direct_path` option 😊 https://github.com/fastlane-community/xcov/blob/master/lib/xcov/options.rb#L76-L86

**Comment by abotkin-cpi** [comment]
Ah, you're right.  I was looking at the description from xcov 1.5.1 still which didn't mention xcresult.  Closing.
