### ISSUE TITLE
Xcode 11 issue - Xcov exited with-out reason. 

### ISSUE THREAD

**Issue by chinnasamymca** [fastlane-community/xcov#159]
+-----------------------------+-----------------------------------------------------------------------------------------------------------+
|                                                         Summary for xcov 1.6.0                                                          |
+-----------------------------+-----------------------------------------------------------------------------------------------------------+
| workspace                   | ./XXX.xcworkspace                                                                                     |
| derived_data_path           | ./build                                                                                                   |
| scheme                      | XXX-BetaTests                                                                                         |
| output_directory            | fastlane/xcov                                                                                             |
| ignore_file_path            | .xcov-ignore-path                                                                                         |
| minimum_coverage_percentage | 30.0                                                                                                      |
| html_report                 | true                                                                                                      |
| markdown_report             | false                                                                                                     |
| json_report                 | false                                                                                                     |
| skip_slack                  | false                                                                                                     |
| slack_username              | xcov                                                                                                      |
| slack_message               | Your *xcov* coverage report                                                                               |
| include_test_targets        | false                                                                                                     |
| only_project_targets        | false                                                                                                     |
| disable_coveralls           | false                                                                                                     |
| ideFoundationPath           | /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation |
| legacy_support              | false                                                                                                     |
+-----------------------------+-----------------------------------------------------------------------------------------------------------+

[02:41:45]: $ /Users/administrator/.gem/gems/xcov-1.6.0/lib/xcov-core/bin/xcov-core -s /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-1493-lafcd9/action_0.xccovreport -o fastlane/xcov/tmp/report.json20191024-1493-1d7kn9p --ide-foundation-path /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
[02:41:45]: ▸ Loading...
[02:41:46]: ▸ Opening .xccoverage file at path: /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-1493-lafcd9/action_0.xccovreport
[02:41:46]: ▸ Parsing .xccoverage file...
[02:41:46]: ▸ File successfully parsed
Opening .xccoverage file at path: /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-1493-lafcd9/action_0.xccovreport
Parsing .xccoverage file...
File successfully parsed
[02:41:46]: Exit status: 
+----------------------------+------------------+
|                 Lane Context                  |
+----------------------------+------------------+
| DEFAULT_PLATFORM           | ios              |
| PLATFORM_NAME              | ios              |
| LANE_NAME                  | ios test_project |
| SCAN_DERIVED_DATA_PATH     | ./build          |
| SCAN_GENERATED_PLIST_FILES | []               |
| SCAN_GENERATED_PLIST_FILE  |                  |
+----------------------------+------------------+
[02:41:46]: Error creating your coverage report - see the log above

I unable to find out the issue, Its just exited after the `File successfully parsed`  , How to debug this issue ?

**Comment by joshdholtz** [comment]
@chinnasamymca Can you try running with `--verbose` at the end of you command? That _should_ hopefully give us some more info 🤞

**Comment by chinnasamymca** [comment]
i got below logs. 

INFO [2019-10-24 11:49:26.85]: $ /Users/administrator/.gem/gems/xcov-1.6.0/lib/xcov-core/bin/xcov-core -s /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-54942-1xomq1e/action_0.xccovreport -o fastlane/xcov/tmp/report.json20191024-54942-v96hjk --ide-foundation-path /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
INFO [2019-10-24 11:49:26.85]: ▸ Loading...
INFO [2019-10-24 11:49:27.90]: ▸ Opening .xccoverage file at path: /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-54942-1xomq1e/action_0.xccovreport
INFO [2019-10-24 11:49:27.90]: ▸ Parsing .xccoverage file...
INFO [2019-10-24 11:49:27.91]: ▸ File successfully parsed
Opening .xccoverage file at path: /var/folders/jh/tlzjnx212c1fxmhz7flhmspc0000gn/T/d20191024-54942-1xomq1e/action_0.xccovreport
Parsing .xccoverage file...
File successfully parsed
ERROR [2019-10-24 11:49:27.91]: Exit status: 
WARN [2019-10-24 11:49:27.91]: Lane Context:
INFO [2019-10-24 11:49:27.91]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test_project", :SCAN_DERIVED_DATA_PATH=>"./derived_data", :SCAN_GENERATED_PLIST_FILES=>[], :SCAN_GENERATED_PLIST_FILE=>nil}
ERROR [2019-10-24 11:49:27.91]: Error creating your coverage report - see the log above
INFO [2019-10-24 11:49:27.91]: Successfully generated documentation at path '/Users/administrator/builds/cS8sSzJL/0/firstrowcorp/seesuit-ios/fastlane/README.md'

**Comment by colinhumber** [comment]
Same issue here. Let me know if I can provide any more info. My stack trace is the same as above, failing on `xcov-1.6.0/lib/xcov-core.rb:30`

**Comment by chinnasamymca** [comment]
Note: This issue happens after upgraded to mac os catalina and Xcode 11

**Comment by slc1973** [comment]
> Note: This issue happens after upgraded to mac os catalina and Xcode 11

I can confirm it. Hope, bugfix is coming soon...

**Comment by NikitaZamalyutdinov** [comment]
Reproduced for me too on Catalina. I've tried to downgrade to 1.5.0 (before Xcode 11 xcresult support added), but it's still failing with the same stacktrace.

**Comment by dannypier** [comment]
Same experience here with the stack trace above. Catalina and XCode 11.1. Happy to provide more info if possible.

**Comment by spencerwhyte** [comment]
Same experience here. The problem occurred when upgrading to Catalina.

The bug is in xcov-core and has to do with relative paths. There is a pull request open here which fixes the problem: https://github.com/fastlane-community/xcov-core/pull/15

**Comment by joshdholtz** [comment]
There will be a new release for this out in a bit 😊

**Comment by joshdholtz** [comment]
This has been released in version `1.7.0` 💪

**Comment by colinhumber** [comment]
Works like a charm. Thanks @joshdholtz and everyone else who work on the fix!
