### ISSUE TITLE
Total coverage calculation method is not correct

### ISSUE THREAD

**Issue by imaginaris** [fastlane-community/xcov#174]
Example:
Source with 3 files:
File 1 - 1 executable line, 1 covered line
File 2 - 1000000 executable lines, 500000 covered lines
File 3 - 1 executable line, 1 covered line

Expected total coverage: (500000 + 1 + 1) / (1000000 + 1 + 1) = ~50%
Actual total coverage: (500000 / 1000000 + 1 / 1 + 1 / 1) / 3 = ~83.33%

Here is the line that does the calculation:
https://github.com/fastlane-community/xcov/blob/e5138422c9555c9eb8fe5a79be685e2bf95390f1/lib/xcov/model/target.rb#L13

I could make a PR but I'd have to modify JSON structure that `xcov-core` creates by crating a PR in https://github.com/fastlane-community/xcov-core and then update the binary here.
But I'm not sure if this is the fastest way.

**Comment by imaginaris** [comment]
Ok so I couldn't wait (lol)
Here are the PRs:
https://github.com/fastlane-community/xcov/pull/175
https://github.com/fastlane-community/xcov-core/pull/17

**Comment by asimparvez** [comment]
Hey @imaginaris , for me there is a difference between the coverage results reported when I run the results in XCode, from what xcov reports.
17.4% in XCode coverage
19% using xcov
could this be the reason? 
Have you checked the XCode coverage calculation? Is it different?

**Comment by imaginaris** [comment]
Hey @asimparvez. Yes that was one of the reasons. In my case coverage from Xcode was around 15% lower that xcov's. The number of files and their respective coverage were the same.
