### ISSUE TITLE
xcov action fails with error Could not find option 'skip_package_dependencies_resolution' in the list of available options fastlane 2.172.0

### ISSUE THREAD

**Issue by AleMaMi** [fastlane-community/xcov#189]
After update fastlane from 2.171.0 to 2.172.0 xcov does not work anymore, it raises error
```
 Could not find option 'skip_package_dependencies_resolution' in the list of available options: workspace, project, scheme, configuration, source_directory, derived_data_path, xccov_file_direct_path, output_directory, cloned_source_packages_path, html_report, markdown_report, json_report, minimum_coverage_percentage, slack_url, slack_channel, skip_slack, slack_username, slack_message, ignore_file_path, include_test_targets, exclude_targets, include_targets, only_project_targets, disable_coveralls, coveralls_service_name, coveralls_service_job_id, coveralls_repo_token, xcconfig, ideFoundationPath, legacy_support
```

Reproduction: run ` bundle exec fastlane run xcov` with fastlane 2.172.0 update.

**Comment by jsaadep** [comment]
I am having the same error, I tried reverting fastlane to previous version but it does not resolve it.
It seems an issue with `scan`

**Comment by vyasanirudh** [comment]
using `2.171.0` solved for me though.

**Comment by jsaadep** [comment]
Yes, it seems it did after all, it was issue in cache.

**Comment by umarchohan** [comment]
I am having the same issue.

**Comment by stherold** [comment]
@jsaadep do you mean your CI cache?

**Comment by stherold** [comment]
Having the same issue :(

**Comment by ainame** [comment]
I figured out the root cause https://github.com/fastlane/fastlane/pull/17916 
 I will work on resolving this issue within fastlane/fastlane.

**Comment by THIRISANGU** [comment]
Facing the same issue with 2.172.0!

**Comment by ainame** [comment]
The PR is ready to review. 
https://github.com/fastlane/fastlane/pull/18053

In the meantime, please use fastlane 2.171.0 for now.

**Comment by ainame** [comment]
https://github.com/fastlane/fastlane/pull/18053 got merged and 2.174.0 is out now.

**Comment by AleMaMi** [comment]
Great job, it works again. Thanks a lot.

**Comment by THIRISANGU** [comment]
Thanks, @ainame.

**Comment by ainame** [comment]
@AleMaMi Would you mind close this issue? 😇

**Comment by AleMaMi** [comment]
Ah! It's my responsibility. Sure!
